// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHxcIZ6RaIhwSgoxjSg810P2OZDEVBm4',
    appId: '1:224514314880:android:907a155acf17be52cc4c65',
    messagingSenderId: '224514314880',
    projectId: 'todo-app-b8431',
    storageBucket: 'todo-app-b8431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx85MAmE82FvGeOzdNp2evOPLldERQmJY',
    appId: '1:224514314880:ios:6b46af2859b5dc88cc4c65',
    messagingSenderId: '224514314880',
    projectId: 'todo-app-b8431',
    storageBucket: 'todo-app-b8431.appspot.com',
    iosBundleId: 'com.kongvong.todoApp2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrWJgZfF6rHcKcOCvrjtzs-15oJ4aGcY',
    appId: '1:224514314880:web:6d22d5f5e7627fe8cc4c65',
    messagingSenderId: '224514314880',
    projectId: 'todo-app-b8431',
    authDomain: 'todo-app-b8431.firebaseapp.com',
    storageBucket: 'todo-app-b8431.appspot.com',
  );

}